
version: "3"

volumes:
  node_modules:

services:
  web:
    build: .
    container_name: breakpad_web
    environment:
        HOME: /home/app
        # -- Alt 2 begin--
        VIRTUAL_HOST: {domain/subdomain}
        # -- Alt 2 end --
    links:
      - db
    network_mode: "bridge"
    # -- Alt 1 begin--
    ports:
        - "{os port}:4000"
    # -- Alt 1 end --
    tty: true
    restart: always
    volumes:
      - .:/home/app/breakpad
      - node_modules:/home/app/breakpad/node_modules
    expose:
      - "4000"
    
  db:
    image: postgres:9.6
    container_name: breakpad_db
    environment:
        POSTGRES_PASSWORD: secret
        POSTGRES_USER: breakpad
        PGDATA: /var/lib/postgresql/data
    network_mode: "bridge"
    ports:
        - "5433:5432"
    restart: always
    volumes:
        - ./postrgres/data:/var/lib/postgresql/data
        - ./postgres/dumpall:/dumpall
